version: "3"
services:
    airflow-web:
        image: "apache/airflow:1.10.12-python3.7"
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
            #- AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
        volumes:
            - ./volumes/airflow:/opt/airflow
            #- ../dags:/opt/airflow/dags
            #- ../logs:/opt/airflow/logs
        # upgradedb applies migrations/inits db if necessary and is safe to run multiple times
        command: ["bash",  "-c", "airflow upgradedb && airflow webserver"]


    db:
        image: postgres:10
        restart: always
        environment:
            # Admin user
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow_db
        volumes:
            - ./volumes/postgres/data:/var/lib/postgresql/data
